// Code generated by mockery v1.0.0
package mocks

import chef "github.com/go-chef/chef"
import mock "github.com/stretchr/testify/mock"

// DataBagService is an autogenerated mock type for the DataBagService type
type DataBagService struct {
	mock.Mock
}

// GetItem provides a mock function with given fields: _a0, _a1
func (_m *DataBagService) GetItem(_a0 string, _a1 string) (chef.DataBagItem, error) {
	ret := _m.Called(_a0, _a1)

	var r0 chef.DataBagItem
	if rf, ok := ret.Get(0).(func(string, string) chef.DataBagItem); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chef.DataBagItem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
